# Generated by Django 5.1.3 on 2024-11-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0002_alter_module_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userassignment',
            name='can_view',
            field=models.BooleanField(default=False),
        ),
    ]
