# Generated by Django 5.1.3 on 2024-11-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submodule',
            name='session',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
