# Generated by Django 5.1.3 on 2024-11-19 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0002_submodule_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='submodule',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
